import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { PropsWithChildren } from "react";
import { layoutServerStorage } from "@/context/layout.storage.server";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const LayoutStateVocabProvider = layoutServerStorage.StateVocabProvider

export default async function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <LayoutStateVocabProvider
          value={{
            session: {
              id: 12345
            }
          }}
        >
          {children}
        </LayoutStateVocabProvider>
      </body>
    </html>
  );
}
