export const STATE_DEFINITION = Symbol("state-def")
export const STATE_PATH = Symbol("state-path")
export const STATE_VERBOSE = Symbol("state-verbose")
export const STATE_VERBOSE_PATH = Symbol("state-verbose-path")
export const STATE_SSR = Symbol("state-ssr")
